/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
-/ 

/-
Formalization of stereographic projection.
We define the sphere S of radius r, the north pole N, 
and the stereographic projection P from the plane to S \ {N}.
We also define the inverse map Q and prove that P and Q are 
inverses, establishing a bijection. Finally, we provide a 
complex number formulation and show it is equivalent to the real formulation.
-/

import Mathlib.Tactic

set_option linter.style.refine false

noncomputable section

open Complex Real Set

/-
Definitions of the sphere S, the north pole N, 
the stereographic projection P, and its inverse Q.
-/


variable (r : ℝ)

-- sphere of radius r, centered at (0,0,r)
def S : Set (ℝ × ℝ × ℝ) := { p | p.1^2 + p.2.1^2 + (p.2.2 - r)^2 = r^2 }

-- The north pole of S
def N (r : ℝ) : ℝ × ℝ × ℝ := (0, 0, 2 * r)

-- Projection of a point on the plane onto S
def P (p : ℝ × ℝ) : ℝ × ℝ × ℝ :=
  let x := p.1
  let y := p.2
  let den := 4 * r^2 + x^2 + y^2
  (4 * r^2 * x / den, 4 * r^2 * y / den, 2 * r * (x^2 + y^2) / den)



-- The inverse of projection function P
def Q (p : ℝ × ℝ × ℝ) : ℝ × ℝ :=
  let α := p.1
  let β := p.2.1
  let γ := p.2.2
  let den := 2 * r - γ
  (2 * r * α / den, 2 * r * β / den)


/-
The image of the stereographic projection P lies in the punctured sphere S \ {N}.
-/
theorem P_range (h_r : r > 0) (p : ℝ × ℝ) : P r p ∈ S r \ {N r} := by
  -- Substitute the coordinates of $P(p)$ into the equation of the sphere $S$.
  have h_sphere : (4 * r^2 * p.1 / (4 * r^2 + p.1^2 + p.2^2))^2 
    + (4 * r^2 * p.2 / (4 * r^2 + p.1^2 + p.2^2))^2 
    + (2 * r * (p.1^2 + p.2^2) / (4 * r^2 + p.1^2 + p.2^2) - r)^2 = r^2 := by
    grind;
  unfold P S N; aesop;

/-
The composition P ∘ Q is the identity on the punctured sphere S \ {N}.
-/
theorem P_left_inv (h_r : r > 0) (p : ℝ × ℝ × ℝ) (hp : p ∈ S r \ {N r})
    : P r (Q r p) = p := by
  unfold P Q S at *;
  by_cases h : 2 * r - p.2.2 = 0 <;> simp_all +decide [ sub_eq_iff_eq_add ];
  · exact False.elim <| hp.2 <| Prod.mk_inj.mpr 
      ⟨ by nlinarith, Prod.mk_inj.mpr ⟨ by nlinarith, by nlinarith ⟩ ⟩;
  · field_simp;
    grind

/-
The composition Q ∘ P is the identity on the complex plane R^2.
-/
theorem P_right_inv (h_r : r > 0) (p : ℝ × ℝ) : Q r (P r p) = p := by
  unfold Q P;
  field_simp;
  norm_num [ mul_comm, h_r.ne' ]

/-
The stereographic projection P induces a bijection between R^2 and the punctured sphere S \ {N}.
-/
def S_minus_N (r : ℝ) : Set (ℝ × ℝ × ℝ) := S r \ {N r}

def P_to_S (h_r : r > 0) (p : ℝ × ℝ) : S_minus_N r := ⟨P r p, P_range r h_r p⟩

theorem P_bijective (h_r : r > 0) : Function.Bijective (P_to_S r h_r) := by
  constructor;
  · intro p q h_eq;
    unfold P_to_S at h_eq;
    have := P_right_inv r h_r p; have := P_right_inv r h_r q; aesop;
  · intro p; have := P_left_inv r h_r p; unfold P_to_S at *; aesop;

/-
The complex definition of stereographic projection is equivalent to the real definition.
-/

def P_complex (z : ℂ) : ℝ × ℝ × ℝ :=
  let den := 4 * r^2 + ‖z‖^2
  (4 * r^2 * z.re / den, 4 * r^2 * z.im / den, 2 * r * ‖z‖^2 / den)

theorem P_complex_eq_P (z : ℂ) : P_complex r z = P r (z.re, z.im) := by
  unfold P_complex P;
  norm_num [ Complex.normSq, Complex.sq_norm ] ; ring_nf;
  norm_num



def IsCircleOrLine (s : Set (ℝ × ℝ)) : Prop :=
  ∃ A B C D : ℝ, (A ≠ 0 ∨ B ≠ 0 ∨ C ≠ 0) ∧
    s = { p | A * (p.1^2 + p.2^2) + B * p.1 + C * p.2 + D = 0 }

def IsPlaneSection (r : ℝ) (s : Set (ℝ × ℝ × ℝ)) : Prop :=
  ∃ a b c d : ℝ, (a ≠ 0 ∨ b ≠ 0 ∨ c ≠ 0) ∧
    s = S r ∩ { p | a * p.1 + b * p.2.1 + c * p.2.2 = d }

/-
A point p satisfies the circle/line equation defined by A, B, C, D 
if and only if its stereographic projection P(p) satisfies the plane
equation defined by a, b, c, d, where a, b, c, d are derived from A, B, C, D.
-/
lemma stereographic_equation_iff (r : ℝ) (hr : r ≠ 0) (A B C D : ℝ) :
  let a := -B
  let b := -C
  let c := (D - 4 * r^2 * A) / (2 * r)
  let d := D
  ∀ p : ℝ × ℝ,
    A * (p.1^2 + p.2^2) + B * p.1 + C * p.2 + D = 0 ↔
    let q := P r p
    a * q.1 + b * q.2.1 + c * q.2.2 = d := by
  unfold P;
  field_simp;
  grind

/-
The stereographic projection P maps circles and lines in the plane 
to plane sections of the sphere S (excluding the north pole).
-/
theorem stereographic_preserves_circle_line (r : ℝ) (hr : r > 0)
(s : Set (ℝ × ℝ)) (h : IsCircleOrLine s) :
    ∃ s', IsPlaneSection r s' ∧ P r '' s = s' \ {N r} := by
  obtain ⟨ A, B, C, D, hD, hs ⟩ := h;
  by_cases h : -B = 0 ∧ -C = 0 ∧ ( D - 4 * r ^ 2 * A ) / ( 2 * r ) = 0;
  · simp_all +decide [ div_eq_iff, hr.ne' ];
    -- Since $A \neq 0$, we can divide both sides of the equation 
    -- $A * (p.1^2 + p.2^2) + 4 * r^2 * A = 0$ by $A$ to get $p.1^2 + p.2^2 + 4 * r^2 = 0$.
    have h_eq : {p : ℝ × ℝ | A * (p.1 ^ 2 + p.2 ^ 2) + 4 * r ^ 2 * A = 0} = ∅ := by
      exact Set.eq_empty_of_forall_notMem fun p hp => hD <| 
        by nlinarith [ hp.symm, sq_nonneg p.1, sq_nonneg p.2, mul_pos hr hr ] ;
    simp_all +decide [ sub_eq_iff_eq_add ];
    refine' ⟨ ∅, _, _ ⟩ <;> norm_num;
    use 0, 0, 1, 3 * r;
    norm_num [ S ];
    exact Eq.symm ( Set.eq_empty_of_forall_notMem fun p hp => 
      by nlinarith [ hp.1.symm, hp.2.symm ] );
  · refine' ⟨ S r ∩ { p : ℝ × ℝ × ℝ | -B * p.1 + -C * p.2.1 
       + ( D - 4 * r ^ 2 * A ) / ( 2 * r ) * p.2.2 = D }, _, _ ⟩;
    · use -B, -C, ( D - 4 * r ^ 2 * A ) / ( 2 * r ), D;
      grind;
    · ext ⟨ x, y, z ⟩;
      constructor;
      · rintro ⟨ p, hp, rfl, rfl, rfl ⟩;
        refine' ⟨ ⟨ _, _ ⟩, _ ⟩ <;> simp_all +decide [ S, N ];
        · -- Combine like terms and simplify the expression.
          field_simp
          ring;
        · field_simp;
          cases lt_or_ge D 0 <;> nlinarith;
        · grind;
      · intro hxyz
        obtain ⟨p, hp⟩ : ∃ p : ℝ × ℝ, P r p = (x, y, z) := by
          -- By definition of $P$, we know that if $(x, y, z) 
          -- \in S r \setminus \{N r\}$, then there exists 
          -- $p \in \mathbb{R}^2$ such that $P r p = (x, y, z)$.
          have h_inv : ∀ x y z : ℝ, (x, y, z) ∈ S r ∧ 
              (x, y, z) ≠ N r → ∃ p : ℝ × ℝ, P r p = (x, y, z) := by
            intros x y z hxyz
            use ( (2 * r * x) / (2 * r - z), (2 * r * y) / (2 * r - z) );
            unfold P S at *;
            by_cases h : 2 * r - z = 0 <;> simp_all +decide [ mul_div_assoc ];
            · exact False.elim <| hxyz.2 <| Prod.mk_inj.mpr 
                ⟨ by nlinarith, Prod.mk_inj.mpr ⟨ by nlinarith, by nlinarith ⟩ ⟩;
            · grind;
          exact h_inv x y z ⟨ hxyz.1.1, hxyz.2 ⟩;
        have := stereographic_equation_iff r hr.ne' A B C D p; aesop;
