/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
-/

/-
This module proves that a complex function is complex differentiable at a point if and only if it is real differentiable at that point and satisfies the Cauchy-Riemann equations.
-/

import Mathlib.Tactic
import Mathlib.Analysis.Complex.Conformal

set_option linter.mathlibStandardSet false

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check differentiableAt_complex_iff_differentiableAt_real

/-
f(z) is complex differentiable at z_0 if and only if the vector function (u(x, y), v(x, y)) is real-differentiable at (x_0, y_0) and the partial derivatives satisfy the Cauchy-Riemann equations u_x = v_y, u_y = -v_x at (x_0,y_0).
-/
theorem complex_differentiable_iff_real_differentiable_and_CR (f : ℂ → ℂ) (z₀ : ℂ) :
  DifferentiableAt ℂ f z₀ ↔
  DifferentiableAt ℝ f z₀ ∧
  let u_x := (fderiv ℝ f z₀ 1).re
  let v_x := (fderiv ℝ f z₀ 1).im
  let u_y := (fderiv ℝ f z₀ Complex.I).re
  let v_y := (fderiv ℝ f z₀ Complex.I).im
  u_x = v_y ∧ u_y = -v_x := by
  refine ⟨ fun hf ↦ ⟨ hf.restrictScalars ℝ, ?_ ⟩, fun hf ↦ ?_ ⟩;
  · -- By definition of the derivative, we know that
    have h_deriv : fderiv ℝ f z₀ = (fderiv ℂ f z₀).restrictScalars ℝ := by
      exact DifferentiableAt.fderiv_restrictScalars ℝ hf;
    aesop;
  · have h_complex_diff : HasFDerivAt f (fderiv ℝ f z₀) z₀ := by
      exact hf.1.hasFDerivAt
    have h_cauchy_riemann : ∃ c : ℂ, fderiv ℝ f z₀ = c • ContinuousLinearMap.smulRight (1 : ℂ →L[ℝ] ℂ) 1 := by
      have h_cauchy_riemann : ∀ x y : ℝ, fderiv ℝ f z₀ (x + y * Complex.I) = (fderiv ℝ f z₀ 1) * x + (fderiv ℝ f z₀ Complex.I) * y := by
        intro x y; rw [ show ( x + y * Complex.I : ℂ ) = x • 1 + y • Complex.I by simp ] ; rw [ map_add, map_smul, map_smul ] ; ring_nf;
        simp +decide [ mul_comm ];
      use (fderiv ℝ f z₀ 1);
      ext x; specialize h_cauchy_riemann x.re x.im; simp_all [ Complex.ext_iff ] ; ring_nf; aesop;
    obtain ⟨c, hc⟩ := h_cauchy_riemann
    have h_complex_diff : HasFDerivAt f (c • ContinuousLinearMap.smulRight (1 : ℂ →L[ℂ] ℂ) 1) z₀ := by
      convert h_complex_diff using 1;
      ext; simp [hc];
      simp [ hasFDerivAt_iff_isLittleO_nhds_zero ]
    exact h_complex_diff.differentiableAt
