/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
-/


/-
 L'hospital rule for 0/0 
 The proof works for complex variable and for real variable. 
 We can comment out the line `{f g : ℂ → ℂ} {z₀ f' g' : ℂ}` and replace it with `{f g : ℝ → ℝ} {z₀ f' g' : ℝ}`, and
 the same proof will work.
-/

import Mathlib.Tactic
import Mathlib.Analysis.Complex.Conformal

noncomputable section

open Complex Filter Topology

/-- 
L'Hôpital's Rule for complex differentiable functions at a point where both vanish.
If f(z₀) = 0, g(z₀) = 0, and g'(z₀) ≠ 0, then lim (f(z)/g(z)) = f'(z₀)/g'(z₀).
-/
theorem complex_lhopital_zero_zero
--    {f g : ℝ → ℝ} {z₀ f' g' : ℝ}
    {f g : ℂ → ℂ} {z₀ f' g' : ℂ}
    (hf : HasDerivAt f f' z₀)
    (hg : HasDerivAt g g' z₀)
    (hf0 : f z₀ = 0)
    (hg0 : g z₀ = 0)
    (hg_ne : g' ≠ 0) :
    Tendsto (fun z ↦ f z / g z) (𝓝[≠] z₀) (𝓝 (f' / g')) := by

  -- By definition of the derivative, we know that 
  -- $\lim_{z \to z_0} \frac{f(z) - f(z_0)}{z - z_0} = f'(z_0)$ 
  -- and $\lim_{z \to z_0} \frac{g(z) - g(z_0)}{z - z_0} = g'(z_0)$.
  have h_deriv : Filter.Tendsto (fun z => (f z - f z₀) / (z - z₀)) (nhdsWithin z₀ {z₀}ᶜ) (nhds f') 
    ∧ Filter.Tendsto (fun z => (g z - g z₀) / (z - z₀)) (nhdsWithin z₀ {z₀}ᶜ) (nhds g') := by
    -- By definition of HasDerivAt, we know that the limit of (f(z) - f(z₀)) / (z - z₀) as z approaches z₀ is f', and similarly for g.
    have h_deriv_f : Filter.Tendsto (fun z => (f z - f z₀) / (z - z₀)) 
      (nhdsWithin z₀ {z₀}ᶜ) (nhds f') := by
      rw [ hasDerivAt_iff_tendsto_slope ] at hf
      simpa [ div_eq_inv_mul ] using hf
    have h_deriv_g : Filter.Tendsto (fun z => (g z - g z₀) / (z - z₀))
      (nhdsWithin z₀ {z₀}ᶜ) (nhds g') := by
      rw [ hasDerivAt_iff_tendsto_slope ] at hg
      simpa [ div_eq_inv_mul ] using hg
    exact ⟨h_deriv_f, h_deriv_g⟩
  -- Since the denominator is non-zero, we can apply the fact that 
  -- the limit of a quotient is the quotient of the limits.
  have h_quot : Filter.Tendsto (fun z => ((f z - f z₀) / (z - z₀)) / ((g z - g z₀) / (z - z₀))) 
    (nhdsWithin z₀ {z₀}ᶜ) (nhds (f' / g')) := by
    exact h_deriv.1.div h_deriv.2 hg_ne

  -- Apply the congruence rule. 
  -- This allows us to prove the limits are the same if the functions are equal near z₀.
  apply h_quot.congr'

  -- Filter to the set of points where z ≠ z₀.
  -- The filter 𝓝[≠] z₀ guarantees we only care about z where z ≠ z₀.
  filter_upwards [self_mem_nhdsWithin] with z hz

  -- Substitute f(z₀) = 0 and g(z₀) = 0 and simplify "something - 0"
  simp only [hf0, hg0, sub_zero]

  -- Perform the algebraic cancellation of (z - z₀).
  -- We need to establish that the denominator (z - z₀) is not zero.
  have h_ne : z - z₀ ≠ 0 := sub_ne_zero.mpr hz
  
  -- Use field_simp to cancel the common factor.
  -- Alternatively, you could use: rw [div_div_div_cancel_right _ _ h_ne]
  field_simp [h_ne]



/-- 
Definition: A function g has a zero of order m at z₀ if 
its first m-1 derivatives vanish, and the m-th derivative is non-zero.
-/
def HasZeroOrder (g : ℂ → ℂ) (z₀ : ℂ) (m : ℕ) : Prop :=
  (∀ k < m, iteratedDeriv k g z₀ = 0) ∧ (iteratedDeriv m g z₀ ≠ 0)

/-
Checking definitions of iteratedDeriv, HasDerivAt, and deriv.
-/
#check iteratedDeriv
#check HasDerivAt
#check deriv

/-
L'Hopital's rule for complex functions at a point where 
the denominator has a simple zero (order 1). The formula f'/g' 
is valid only for m=1.
-/
open Filter Topology

theorem complex_lhopital_zero_zero'
    {f g : ℂ → ℂ} {z₀ f' g' : ℂ}
    (hf : HasDerivAt f f' z₀)
    (hg : HasDerivAt g g' z₀)
    (hf0 : f z₀ = 0)
    (hg0 : g z₀ = 0)
    (m : ℕ) (hm : m = 1)
    (hg_zero_order : HasZeroOrder g z₀ m) :
    Tendsto (fun z ↦ f z / g z) (𝓝[≠] z₀) (𝓝 (f' / g')) := by
      rw [ hasDerivAt_iff_tendsto_slope_zero ] at hf hg;
      -- We'll use the fact that if the denominator is non-zero and the numerator tends to a limit, then the quotient tends to the quotient of the limits.
      have h_div : Filter.Tendsto (fun t => (f (z₀ + t) - f z₀) / (g (z₀ + t) - g z₀)) (nhdsWithin 0 {0}ᶜ) (nhds (f' / g')) := by
        have h_div : Filter.Tendsto (fun t => (f (z₀ + t) - f z₀) / t / ((g (z₀ + t) - g z₀) / t)) (nhdsWithin 0 {0}ᶜ) (nhds (f' / g')) := by
          convert hf.div hg _ using 1;
          · ext; simp +decide [ div_eq_inv_mul ] ;
          · simp_all +decide [ HasZeroOrder ];
            contrapose! hg_zero_order; rw [ show deriv g z₀ = g' by exact ( HasDerivAt.deriv <| by rw [ hasDerivAt_iff_tendsto_slope_zero ] ; simpa [ div_eq_inv_mul, hg0 ] using hg ) ] ; aesop;
        refine' h_div.congr' ( by filter_upwards [ self_mem_nhdsWithin ] with t ht using by rw [ div_div_div_cancel_right₀ ht ] );
      rw [ Metric.tendsto_nhdsWithin_nhds ] at *;
      intro ε hε; rcases h_div ε hε with ⟨ δ, hδ, H ⟩ ; exact ⟨ δ, hδ, fun { x } hx₁ hx₂ => by simpa [ * ] using H ( sub_ne_zero_of_ne hx₁ ) <| by simpa [ dist_eq_norm ] using hx₂ ⟩ ;

