/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2369b963-eace-494e-b8ce-1346a6f44ada

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of a distributed computing system model with decodability and secrecy requirements.

The model includes:
- `mutualInformation`: Definition of mutual information using Kullback-Leibler divergence.
- `DistributedComputingSystem`: A structure capturing the system parameters, encoding function, decodability requirement (recovery from any K workers), and secrecy requirement (bounded mutual information for any J colluding workers).

The formalization handles the matrix dimensions, random keys, and probability measures as specified. The secrecy condition quantifies over all valid probability distributions for the matrix entries (i.i.d. with bounded second moment and existing PDF).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of mutual information between two random variables X and Y on a probability space (Ω, μ).
-/
open MeasureTheory ProbabilityTheory InformationTheory Real Matrix

noncomputable def mutualInformation {Ω E F : Type*} [MeasurableSpace Ω] [MeasurableSpace E] [MeasurableSpace F]
  (μ : Measure Ω) (X : Ω → E) (Y : Ω → F) : ENNReal :=
  let P_XY := μ.map (fun ω => (X ω, Y ω))
  let P_X := μ.map X
  let P_Y := μ.map Y
  klDiv P_XY (P_X.prod P_Y)

/-
Formalization of the distributed computing system model with decodability and secrecy requirements, including a local instance for MeasurableSpace Matrix.
-/
open MeasureTheory ProbabilityTheory InformationTheory Real Matrix

instance {m n α : Type*} [MeasurableSpace α] : MeasurableSpace (Matrix m n α) :=
  inferInstanceAs (MeasurableSpace (m → n → α))

structure DistributedComputingSystem (N K J m d m' : ℕ) (r η₀ : ℝ) where
  -- Key space and measure
  KeySpace : Type
  [mKey : MeasurableSpace KeySpace]
  keyMeasure : Measure KeySpace
  [isProb : IsProbabilityMeasure keyMeasure]

  -- Encoding function
  encode : Matrix (Fin m) (Fin d) ℝ → KeySpace → Fin N → Matrix (Fin m') (Fin d) ℝ
  encode_measurable : Measurable (fun (p : Matrix (Fin m) (Fin d) ℝ × KeySpace) => encode p.1 p.2)

  -- Decodability
  decodable : ∀ (S : Finset (Fin N)), S.card = K →
    ∃ (decode : (Fin d → ℝ) → (S → Fin m' → ℝ) → Fin m → ℝ),
      ∀ (A : Matrix (Fin m) (Fin d) ℝ) (k : KeySpace) (x : Fin d → ℝ),
        decode x (fun n => (encode A k n).mulVec x) = A.mulVec x

  -- Secrecy
  secrecy : ∀ (ν : Measure ℝ),
    IsProbabilityMeasure ν →
    (HasPDF id ν volume) →
    (∫ x, x^2 ∂ν ≤ r^2) →
    ∀ (S : Finset (Fin N)), S.card = J →
    let μ_A : Measure (Matrix (Fin m) (Fin d) ℝ) := Measure.pi (fun _ => Measure.pi (fun _ => ν))
    let μ_joint := μ_A.prod keyMeasure
    let A (p : Matrix (Fin m) (Fin d) ℝ × KeySpace) := p.1
    let C_S (p : Matrix (Fin m) (Fin d) ℝ × KeySpace) := fun n : S => encode p.1 p.2 n
    mutualInformation μ_joint A C_S ≤ ENNReal.ofReal (η₀ * m * d)
