/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
-/

/-
This module proves that a complex function is complex differentiable at a point if and only if it is real differentiable at that point and satisfies the Cauchy-Riemann equations.
-/

import Mathlib
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
-- NOTE: The original `synthInstance.maxHeartbeats 20000` was too low to synthesize
-- `IsScalarTower ℝ ℂ ℂ`, which is needed by `DifferentiableAt.restrictScalars` and
-- `DifferentiableAt.fderiv_restrictScalars`. Increasing it to 40000 resolves the
-- "failed to synthesize" errors.
set_option synthInstance.maxHeartbeats 40000
set_option synthInstance.maxSize 256
set_option relaxedAutoImplicit false
set_option autoImplicit false
set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true
set_option grind.warning false
/-
f(z) is complex differentiable at z₀ if and only if the vector function (u(x, y), v(x, y))
is real-differentiable at (x₀, y₀) and the partial derivatives satisfy the Cauchy-Riemann
equations u_x = v_y, u_y = -v_x at (x₀, y₀).
-/
theorem complex_differentiable_iff_real_differentiable_and_CR (f : ℂ → ℂ) (z₀ : ℂ) :
    DifferentiableAt ℂ f z₀ ↔
    DifferentiableAt ℝ f z₀ ∧
    let u_x := (fderiv ℝ f z₀ 1).re
    let v_x := (fderiv ℝ f z₀ 1).im
    let u_y := (fderiv ℝ f z₀ Complex.I).re
    let v_y := (fderiv ℝ f z₀ Complex.I).im
    u_x = v_y ∧ u_y = -v_x := by
  -- Split the iff into forward and backward directions.
  refine ⟨fun hf ↦ ⟨hf.restrictScalars ℝ, ?_⟩, fun hf ↦ ?_⟩
  · -- ══════════════════════════════════════════════════════════════════════
    -- Forward direction: ℂ-differentiable ⟹ ℝ-differentiable + Cauchy-Riemann
    -- ══════════════════════════════════════════════════════════════════════
    -- The real Fréchet derivative equals the complex one restricted to ℝ-scalars.
    -- This gives us the relationship between real and complex partial derivatives.
    have h_deriv : fderiv ℝ f z₀ = (fderiv ℂ f z₀).restrictScalars ℝ :=
      DifferentiableAt.fderiv_restrictScalars ℝ hf
    -- The Cauchy-Riemann equations follow from the ℂ-linearity of fderiv ℂ f z₀:
    -- applying a ℂ-linear map to I·z is the same as I times the map applied to z,
    -- which forces u_x = v_y and u_y = -v_x.
    aesop
  · -- ══════════════════════════════════════════════════════════════════════
    -- Backward direction: ℝ-differentiable + Cauchy-Riemann ⟹ ℂ-differentiable
    -- ══════════════════════════════════════════════════════════════════════
    -- We already know f has a real Fréchet derivative at z₀.
    have h_complex_diff : HasFDerivAt f (fderiv ℝ f z₀) z₀ :=
      hf.1.hasFDerivAt
    -- Key step: the Cauchy-Riemann equations imply that the ℝ-linear derivative
    -- is actually ℂ-linear. We show fderiv ℝ f z₀ = c • id for some c : ℂ.
    -- Concretely, c = fderiv ℝ f z₀ 1 (the derivative in the real direction).
    have h_cauchy_riemann :
        ∃ c : ℂ, fderiv ℝ f z₀ = c • ContinuousLinearMap.smulRight (1 : ℂ →L[ℝ] ℂ) 1 := by
      -- Every z ∈ ℂ decomposes as z = x + y·I, and the ℝ-linear map acts as:
      --   fderiv ℝ f z₀ (x + y·I) = (fderiv ℝ f z₀ 1)·x + (fderiv ℝ f z₀ I)·y
      have h_decomp : ∀ x y : ℝ,
          fderiv ℝ f z₀ (x + y * Complex.I) =
          (fderiv ℝ f z₀ 1) * x + (fderiv ℝ f z₀ Complex.I) * y := by
        intro x y
        rw [show (x + y * Complex.I : ℂ) = x • 1 + y • Complex.I by simp]
        rw [map_add, map_smul, map_smul]
        ring_nf
        simp +decide [mul_comm]
      -- Using the Cauchy-Riemann equations (u_x = v_y, u_y = -v_x), we verify
      -- that multiplication by c = fderiv ℝ f z₀ 1 reproduces the map on all of ℂ.
      use fderiv ℝ f z₀ 1
      ext x
      specialize h_decomp x.re x.im
      simp_all [Complex.ext_iff]
      ring_nf
      aesop
    -- Now we know fderiv ℝ f z₀ = c • id for some c : ℂ.
    obtain ⟨c, hc⟩ := h_cauchy_riemann
    -- Rewrite the HasFDerivAt statement to use the ℂ-linear map c • id,
    -- which is a valid ℂ →L[ℂ] ℂ derivative.
    have h_complex_diff :
        HasFDerivAt f (c • ContinuousLinearMap.smulRight (1 : ℂ →L[ℂ] ℂ) 1) z₀ := by
      convert h_complex_diff using 1
      ext
      simp [hc]
      simp [hasFDerivAt_iff_isLittleO_nhds_zero]
    -- A function with a ℂ-Fréchet derivative is ℂ-differentiable.
    exact h_complex_diff.differentiableAt
